export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_FEATURED_SUCCESS = "GET_FEATURED_SUCCESS";
export const GET_FEATURED_FAILURE = "GET_FEATURED_FAILURE";

export const GET_SEARCHED_SUCCESS = "GET_SEARCHED_SUCCESS";
export const GET_SEARCHED_FAILURE = "GET_SEARCHED_FAILURE";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CUSTOMER_BEARER = "CUSTOMER_BEARER";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const RESET_CART = "RESET_CART";

export const GET_BEARER = "GET_BEARER";

export const ADD_TO_CART_PRODUCT = "ADD_TO_CART_PRODUCT";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const UPDATE_CART_PRODUCT = "UPDATE_CART_PRODUCT";
export const GET_CART_PRODUCT = "GET_CART_PRODUCT";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_FAILURE = "CREATE_CART_FAILURE";

export const SHIPPING_METHOD_SUCCESS = "SHIPPING_METHOD_SUCCESS";
export const SHIPPING_METHOD_FAILURE = "SHIPPING_METHOD_FAILURE";

export const SHIPPING_INFO_SUCCESS = "SHIPPING_INFO_SUCCESS";
export const SHIPPING_INFO_FAILURE = "SHIPPING_INFO_FAILURE";

export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";
